export const GEMINI_MODEL = "gemini-2.5-flash-image";

export const STYLE_PROMPTS = {
  watercolor:
    "(Studio Ghibli art style), (classic hand-drawn watercolor illustration aesthetic), based on the provided photo, transformed into a beloved Ghibli-style anime protagonist, (round face, gentle large expressive eyes, detailed flowing hair), the characters retain their pose and expressions from the original image, the original background is rendered with Studio Ghibli colors and textures but the scene composition remains exactly the same as the input photo, (soft and warm filtered sunlight), (delicate line work), nostalgic atmosphere, (subtle dust motes floating in the air), (resembles a high-quality animation cel from a film like Howl's Moving Castle), cozy and magical feel, high definition art.",

  cartoon:
    "Transform this image into a Disney-style animated feature film character illustration. Use a polished 3D animated movie look with smooth rendering, soft global illumination, and warm cinematic lighting. Redesign the characters with large expressive eyes with bright highlights, rounded soft appealing facial features, and slightly stylized non-realistic proportions. Keep the original identity of each person while enhancing them into charming and appealing animated characters. Skin should be smooth and slightly glossy with soft gradients. Hair should be simplified into clean soft voluminous shapes. Clothing should remain similar but slightly stylized and simplified. Use a warm magical inviting color palette. IMPORTANT: Avoid anime style, avoid flat illustration, avoid realistic human proportions. Maintain a high-quality animated feature film aesthetic. high quality, highly detailed, consistent style, clean composition, no distortion. Background should preserve the original real-world scene exactly as it appears — do not replace, reimagine, or significantly alter the background. Only apply subtle color grading and soft depth-of-field blur to the existing background. The background must remain recognizable and true to the original photo.",

  vllage:
    "Transform this image into an Animal Crossing-style character. Make the character cute and chibi-like with a small body and large round head. Use smooth textures, soft shading, and bright, cheerful colors. Add simple, rounded features with big expressive eyes. Give it a cozy and friendly vibe, like a character from a relaxing village life game. Background should feel clean, minimal, and colorful. high quality, highly detailed, consistent style, clean composition, no distortion",
};
