export const GEMINI_MODEL = "gemini-2.5-flash-image";

export const STYLE_PROMPTS = {
  watercolor:
    "Transform this photo into a frame from a Japanese animated film in a classic Ghibli-inspired style. Use clean and delicate linework with soft, natural shading and warm, slightly muted color tones. Characters should have natural and realistic proportions with slightly larger, gentle eyes and soft facial features. Avoid exaggeration. Skin should appear smooth and softly shaded, not overly textured or painterly. Use subtle gradients and soft lighting to create a calm, nostalgic atmosphere. Hair should be naturally detailed with light, soft strands, not overly simplified. Background should be softly illustrated with warm tones and minimal detail, like an animation scene. Avoid heavy outlines, avoid watercolor textures, avoid overly flat colors. Maintain a balanced look between animation and realism, like a high-quality animated movie still. high quality, highly detailed, consistent style, clean composition, no distortion",

  cartoon:
    "Transform this image into a Disney-style animated feature film character illustration. Use a polished 3D animated movie look with smooth rendering, soft global illumination, and warm cinematic lighting. Redesign the characters with large expressive eyes with bright highlights, rounded soft appealing facial features, and slightly stylized non-realistic proportions. Keep the original identity of each person while enhancing them into charming and appealing animated characters. Skin should be smooth and slightly glossy with soft gradients. Hair should be simplified into clean soft voluminous shapes. Clothing should remain similar but slightly stylized and simplified. Use a warm magical inviting color palette. IMPORTANT: Avoid anime style, avoid flat illustration, avoid realistic human proportions. Maintain a high-quality animated feature film aesthetic. high quality, highly detailed, consistent style, clean composition, no distortion. Background should preserve the original real-world scene exactly as it appears — do not replace, reimagine, or significantly alter the background. Only apply subtle color grading and soft depth-of-field blur to the existing background. The background must remain recognizable and true to the original photo.",

  village:
    "Transform this image into an Animal Crossing: New Horizons style illustration. Redesign all people as Animal Crossing villager characters — they can be transformed into cute animal villagers such as cats, dogs, bears, ducks, rabbits, frogs, hamsters, or other Animal Crossing animal types, with chibi-like proportions, small rounded body, and large round expressive head. Use smooth pastel textures, soft cel-shading, and bright cheerful colors typical of the Animal Crossing game. Add simple rounded facial features with big shiny eyes, cute small nose, and friendly smile. Give each character a cozy warm personality vibe. Clothing should be simplified and stylized in Animal Crossing fashion. The overall feel should be adorable, wholesome, and relaxing like the game itself. IMPORTANT: Transform people into animal villager characters, not human characters. high quality, highly detailed, consistent style, clean composition, no distortion. Background should preserve the original real-world scene exactly as it appears — do not replace, reimagine, or significantly alter the background. Only apply subtle pastel color grading and soft warm lighting to the existing background. The background must remain recognizable and true to the original photo.",
};
